version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: requirements/nginx
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    networks:
      - inception
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env
    expose:
      - "3306"
    restart: on-failure
  wordpress:
    container_name: wordpress
    image: wordpress
    build: requirements/wordpress
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html
    env_file: .env
    expose:
      - "9000"
    depends_on:
      - mariadb
      - nginx
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  wp-data:
    driver: local
    driver_opts:
      device: /home/samunyan/data/wordpress
      o: bind
      type: none
  db-data:
    driver: local
    driver_opts:
      device: /home/samunyan/data/mariadb
      o: bind
      type: none